<?php
/**
 * @file
 * Code for the GSB Feature Club Display feature.
 */

include_once 'gsb_feature_club_display.features.inc';


/**
 * Implements hook_apachesolr_index_document_build_node().
 *
 */
function gsb_feature_club_display_apachesolr_index_document_build_node(ApacheSolrDocument $document, $entity, $env_id) {
  if ($entity->type == 'club') {
    if (!empty($entity->field_body)) {
      $document->setMultiValue('ts_field_body', $entity->field_body['und'][0]['value']);
    }

    if (!empty($entity->field_link_single)) {
      $document->setMultiValue('ss_field_link_single', $entity->field_link_single['und'][0]['url']);
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function gsb_feature_club_display_views_pre_render(&$view) {
  if ($view->name == 'club_filters') {
    $view->exposed_raw_input = array();
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for views_exposed_form().
 */
function gsb_feature_club_display_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['view']->name == 'club_filters') {
    // Exclude the search text field from auto-submit.
    $form['search']['#attributes']['class'][] = 'ctools-auto-submit-exclude';
  }
}

/**
  * Implements hook_form_FORM_ID_alter().
  */
function gsb_feature_club_display_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state) {

  // Alter 'Club add by ID or tag' content pane settings form.
  if ($form_state['pane']->subtype == 'club_filters-club_by_id_or_tag' && $form_state['view']->name == 'club_filters' && $form_state['view']->current_display == 'club_by_id_or_tag') {

    $conf = $form_state['conf'];
    $item['title_link'] = array(
      '#title' => t('URL'),
      '#type' => 'textfield',
      '#weight' => -100,
      '#default_value' => !empty($conf['title_link']) ? $conf['title_link'] : '',
    );
    $form['override_title']['#weight'] = -99;
    $form = gsb_misc_fixes_associative_insert($form, 'override_title_text', $item);

    // Add override values callback absolutely first.
    array_unshift($form['#submit'], 'gsb_feature_club_display_club_nid_tid_pane_submit');
  }
}

/**
 * Form callback.
 *
 * Keep only 1 contextual filter at a time, unset the other.
 */
function gsb_feature_club_display_club_nid_tid_pane_submit($form, &$form_state) {

  // Submit handler for views_content_views_panes_content_type_edit_form.
  // - Save title link field in pane config.
  $form_state['conf']['title_link'] = $form_state['values']['title_link'];
}

/**
 * Implements hook_panels_pane_content_alter().
 *  - Alter 'Club add by ID or tag' content pane title to be linked to a custom URL.
 */
function gsb_feature_club_display_panels_pane_content_alter($content, $pane, $args, $context) {
  if ($content && $content->subtype == 'club_filters-club_by_id_or_tag') {
    if (!empty($pane->configuration['title_link'])) {
      $content->title = l($content->title, $pane->configuration['title_link']);
    }
  }
}

function gsb_feature_club_display_gsb_fpp_customizations_icons_alter(&$icons) {
  $module_path = drupal_get_path('module', 'gsb_feature_club_display');
  $icons_settings = array(
    'views_panes:club_filters-club_by_id_or_tag' => 'club-by-id-or-tag.jpg',
    'views_panes:club_filters-club_list' => 'Club_filters_club_list.png',
  );
  foreach($icons_settings as $key => $value) {
    if (isset($icons[$key]['icon'])) {
      $icons[$key]['icon'] = $module_path . '/images/' . $value;
    }
  }
}
