<?php
/**
 * @file
 * Code for the GSB Feature Club Display feature.
 */

include_once 'gsb_feature_club_display.features.inc';


/**
 * Implements hook_apachesolr_index_document_build_node().
 *
 */
function gsb_feature_club_display_apachesolr_index_document_build_node(ApacheSolrDocument $document, $entity, $env_id) {
  if ($entity->type == 'club') {
    if (!empty($entity->field_body)) {
      $document->setMultiValue('ts_field_body', $entity->field_body['und'][0]['value']);
    }

    if (!empty($entity->field_link_single)) {
      $document->setMultiValue('ss_field_link_single', $entity->field_link_single['und'][0]['url']);
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function gsb_feature_club_display_views_pre_render(&$view) {
  if ($view->name == 'club_filters') {
    $view->exposed_raw_input = array();
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for views_exposed_form().
 */
function gsb_feature_club_display_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['view']->name == 'club_filters') {
    // Exclude the search text field from auto-submit.
    $form['search']['#attributes']['class'][] = 'ctools-auto-submit-exclude';
  }
}

/**
 * Implements hook_form_alter().
 */
function gsb_feature_club_display_form_alter(&$form, &$form_state, $form_id) {

  // Alter 'Club add by ID or tag' content pane settings form.
  if ($form_id == 'views_content_views_panes_content_type_edit_form' && $form_state['pane']->subtype == 'club_filters-club_by_id_or_tag') {

    $default_value = 'nid';
    if (isset($form_state['pane'])) {
      if (isset($form_state['pane']->configuration['exposed'])) {
        $default_value = $form_state['pane']->configuration['exposed']['club_filter_by'];
      }
    }
    
    $form['exposed']['club_filter_by'] = array(
      '#type' => 'radios',
      '#options' => array(
        'nid' => 'Node ID',
        'tid' => 'Term',
      ),
      '#default_value' => $default_value,
      '#weight' => -100,
    );

    $form['exposed']['filter-nid']['#states'] = array(
      'visible' => array(
        ':input[name="exposed[club_filter_by]"]' => array('value' => 'nid'),
      ),
    );
    // Change #id to apply #states.
    $form['exposed']['filter-term_node_tid_depth']['#id'] = 'views-exposed-pane-tid';
    $form['exposed']['filter-term_node_tid_depth']['#states'] = array(
      'visible' => array(
        ':input[name="exposed[club_filter_by]"]' => array('value' => 'tid'),
      ),
    );
    drupal_add_js(drupal_get_path('module', 'gsb_feature_club_display') . '/js/gsb_feature_club_display.js');

    // Add override values callback absolutely first.
    array_unshift($form['#submit'], 'gsb_feature_club_display_club_nid_tid_pane_submit');
  }
}

/**
 * Form callback.
 *
 * Keep only 1 contextual filter at a time, unset the other.
 */
function gsb_feature_club_display_club_nid_tid_pane_submit($form, &$form_state) {
  switch ($form_state['values']['exposed']['club_filter_by']) {
    case 'nid':
      $form_state['values']['exposed']['term_node_tid_depth'] = '';
      break;
    case 'tid':
      $form_state['values']['exposed']['nid'] = '';
      break;
  }
}

function gsb_feature_club_display_gsb_fpp_customizations_icons_alter(&$icons) {
  $module_path = drupal_get_path('module', 'gsb_feature_club_display');
  $icons_settings = array(
    'views_panes:club_filters-club_by_id_or_tag' => 'club-by-id-or-tag.jpg',     
    'views_panes:club_filters-club_list' => 'Club_filters_club_list.png',       
  );
  foreach($icons_settings as $key => $value) {
    if (isset($icons[$key]['icon'])) {
      $icons[$key]['icon'] = $module_path . '/images/' . $value;
    }
  }
}
